version: '3.8'

services:
  # V免签Fox前端服务
  vmqfox-frontend:
    image: hulisang/vmqfox-frontend:latest
    container_name: vmqfox-frontend
    ports:
      - "3006:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - backend
    networks:
      - vmqfox-network

  # V免签Fox后端服务
  backend:
    image: hulisang/vmqfox-backend:latest
    container_name: vmqfox-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - APP_DEBUG=true
      - APP_TRACE=false
      - APP_FRONTEND_URL=http://vmqfox-frontend:3006
      - DB_TYPE=mysql
      - DB_HOSTNAME=172.26.48.46
      - DB_DATABASE=vmq
      - DB_USERNAME=root
      - DB_PASSWORD=mariadb_SwWZ8k
      - DB_HOSTPORT=3306
      - DB_CHARSET=utf8
      - DB_PREFIX=
      - DB_DEBUG=true
      - REDIS_HOST=172.26.48.46
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_PFsA8s
      - REDIS_SELECT=0
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
    networks:
      - vmqfox-network

# 网络配置
networks:
  vmqfox-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
